### ISSUE TITLE
[ha-ezviz] Integration works but i can't add in automation

### ISSUE THREAD

**Issue by Judunet** [RenierM26/ha-ezviz#1]
Hi,

I have an issue with ha-ezviz, i was installed correctly and i can see new ha-ezviz services into the development section in HA. I can call the service with this parameters and it's OK i can control my ezviz device:
`cmd: 0
serial: Dxxxxxx
`

But when i want to integrate this service into an automation, it doesn't work.
I have this message:
**Message malformed: Service ha-ezviz.ezviz_alarm_notify does not match format <domain>.<name> for dictionary value @ data['sequence'][0]['service']
**

Can you help me please.

Thanks a lot.

Regards,

**Comment by RenierM26** [comment]
Hi Judunet,

Please try the latest release, I have added support for the hassio built-in services Works much easier.

"camera.disable_motion_detection" and "camera.enable_motion_detection"

**Comment by RenierM26** [comment]
The other services should be referenced as follows:

      service_data:
        serial: D6XXXXXX         <----the serial number of your camera. Not the entity id.
        cmd: 0                            <------command data. (Best to have a look at services under developer. 0 = disable/ 1 = enable)

All the fields for the service your calling needs to be included in this format.

**Comment by Judunet** [comment]
Hi, 

Thanks for your reply.
I was updated to the last version (now 0.0.1.4). With this new version i lost services like ezviz_alarm_notify.

I'm not sure to understand how i can implement this into HA. I try to add directly in lovelace interface when i choose for example the service ha-ezviz.ezviz_alarm_sound and in "data of services" i put this code:
`
cmd: 1
serial: E36233704
`
Now in development tool in service i don't have one service work with the new version.

Regards,

**Comment by Judunet** [comment]
In development tool, it work fine but not in automation.
For example if i create this automation:

```
- id: 'Cam disarm'
  alias: '[CAM] Disarm notification'
  description: ''
  trigger:
    - entity_id: group.people
      from: not_home
      platform: state
      to: home
  condition: []
  action:
    - data:
        cmd: 0
        serial: Dxxxxx
      service: ha-ezviz.ezviz_switch_audio
  mode: single
```
I get the message when i reload the automations in HA:
`2020-12-27 00:06:17 ERROR (MainThread) [homeassistant.config] Invalid config for [automation]: Service ha-ezviz.ezviz_switch_audio does not match format <domain>.<name> for dictionary value @ data['action'][0]['service']. Got None. (See /config/configuration.yaml, line 9). 
`
