### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by avol-io** [RenierM26/ha-ezviz#15]
```
camera:
  - platform: ezviz_cloud 
    username: xxx@gmail.com
    password: "xxx!!password"
```
 
give me Invalid config for [camera.ezviz_cloud]: [username] is an invalid option for [camera.ezviz_cloud]. Check: camera.ezviz_cloud->username

where I do a mistake?

Can i suggest to add an example of complete configuration to repository if this is different respect https://www.home-assistant.io/integrations/ezviz/
