### ISSUE TITLE
Hassio - Ezviz integration 3.8

### ISSUE THREAD

**Issue by jjhamb** [RenierM26/ha-ezviz#29]
Hi Guys, I have installed EZVIZ integration via HACS and followed example from Repo:
```
stream:
ffmpeg:
camera:

ezviz_cloud:
  cameras:
    D6666660:
      username: admin
      password: Password_from_camera_sticker.
    D666678:
      username: admin
      password: Password_from_camera_sticker.
    D66666648:
      username: admin
      password: Password_from_camera_sticker.
```
Above did not result in any cameras being added.
I went further and amended the yaml to include credentials:

```
ezviz_cloud:
  username: "email@yahoo.com"
  password: "password"
  cameras:
    D6666660:
      username: admin
      password: Password_from_camera_sticker.
    D666678:
      username: admin
      password: Password_from_camera_sticker.
    D66666648:
      username: admin
      password: Password_from_camera_sticker.

```

it still does not generate any cameras...
I am not subscribed to cloudplay service, does that matter?

**Comment by dx44** [comment]
Hi @jjhamb , take a look at this https://github.com/RenierM26/ha-ezviz/issues/27.

**Comment by jjhamb** [comment]
I followed thru the directions:
Added HACS integration. Restarted
Added Integration for EZVIZ and entered my credentials {Region in}
Added Camera to configuration.yaml

```
stream:
ffmpeg:
camera:

ezviz_cloud:
  cameras:
    D6666660:
      username: admin
      password: Password_from_camera_sticker.

```

Still no joy.. :(
