### ISSUE TITLE
no video stream after upgrade to 0.0.4.3

### ISSUE THREAD

**Issue by marcob79** [RenierM26/ha-ezviz#34]
everything was quite fine with version 0.0.3.8 (or .9 I didn't remember).
I have an ezviz C1C

i just upgrade to 0.0.4.3
modified the configuration.yaml as per new indications, like:

```
camera:
- platform: ezviz_cloud
  username: xxxxxxx
  password: yyyyyyyyy
  cameras:
    D123456:
      username: user
      password: password
```

restarted.... removed old from GUI and added it again.
restarted again.
now I have 1 device and all 29 entities.

Entities seems fine, but i cannot get the video stream from the device anymore.
in the log i just see the following:

```
Logger: custom_components.ezviz_cloud.camera
Source: custom_components/ezviz_cloud/camera.py:67
Integration: Ezviz (documentation)
First occurred: 10:00:19 AM (1 occurrences)
Last logged: 10:00:19 AM

Loading ezviz via platform config is deprecated, it will be automatically imported. Please remove it afterwards.
```

**Comment by pete-leese** [comment]
Same issue here.

**Comment by tyron** [comment]
I also have a C1C, upgraded to 0.0.4.3 and all is working. I have that same log message (`Loading ezviz via platform config is deprecated, it will be automatically imported. Please remove it afterwards.`), but it doesn't prevent the functionality on hass.

Make sure you have a `region: xx` (us / eu) on your config. My setup wasn't working before I added the US...

```
camera:
  - platform: ezviz_cloud
    username: !secret ezviz_user
    password: !secret ezviz_pass
    region: us
    cameras:
      D123456789:
        username: admin
        password: !secret ezviz_code
```
